name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: mac
            runner: macos-latest
          - platform: win
            runner: windows-latest
          - platform: linux
            runner: ubuntu-latest
            
    runs-on: ${{ matrix.runner }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
            
      - name: Install Dependencies
        run: bun install

      - name: Run build
        run: bun run build
  
      - name: cd to build directory
        run: cd apps/desktop
        
      # Only decode certificate for platforms that require code signing
      - name: Setup code signing certificate
        if: matrix.platform == 'mac' || matrix.platform == 'win'
        run: |
          echo "$CSC_LINK" | base64 -d > cert.p12
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}

      - name: Build Electron App for ${{ matrix.platform }}
        run: npx electron-builder --${{ matrix.platform }}
        env:
          CSC_LINK: ${{ runner.workspace }}/cert.p12  # pointing to the local file
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ matrix.platform }}-build
          path: dist/*
