name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "22"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: |
          export PRISMA_CLI_QUERY_ENGINE_TYPE=binary
          bun install

      - name: Setup Electron
        run: node ./node_modules/electron/install.js

      - name: Clean build artifacts
        run: rm -rf apps/desktop/dist

      - name: Run build
        run: bun run build --filter desktop

      - name: Build Electron
        run: |
          cd apps/desktop/
          USE_HARD_LINKS=false bunx electron-builder --${{ matrix.os }} --${{ matrix.arch }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-${{ matrix.arch }}
          path: apps/desktop/dist
