name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "22"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: |
          export PRISMA_CLI_QUERY_ENGINE_TYPE=binary
          bun install

      - name: Setup Electron
        run: node ./node_modules/electron/install.js

      - name: Clean build artifacts
        run: rm -rf apps/desktop/dist

      - name: Run build
        run: bun run build --filter desktop

      - name: Build Electron
        run: |
          cd apps/desktop/
          USE_HARD_LINKS=false bunx electron-builder

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: apps/desktop/dist
